<template>
  <p>Welcome to my Triple Yang collection!</p>
  <p>
    I wanted to try Yin-Yang with 3 colors, but I couldn't find any out there,
    so I learned how to use the Z3 Theorem Prover to make some myself.
  </p>
  <p>
    Note that all puzzles available here have been generated by a script that
    systematically removes as many clues as possible while still keeping the
    solution unique. This means they may unexpectedly range between very easy
    and very difficult &mdash; please feel free to skip a puzzle if you're
    stuck. I manually removed some that looked much too easy.
  </p>
  <h1 class="text-lg font-bold">Rules</h1>
  <ol class="list-decimal">
    <li>Every cell must be filled with one of 3 colors.</li>
    <li>
      All cells of the same color must be connected orthogonally into a single
      group.
    </li>
    <li>There must be at least 1 cell of each color.</li>
    <li>2x2 squares of cells of the same color are not allowed.</li>
  </ol>
</template>
