<script setup lang="ts">
import AppLink from "@/components/AppLink.vue";
import IconExternalLink from "@/components/icons/IconExternalLink.vue";
</script>
<template>
  <p>
    Welcome! This is a page I made dedicated to a puzzle called Triple Yang, a
    variant of
    <AppLink href="https://www.puzzle-yin-yang.com/"
      >Yin-Yang<IconExternalLink /></AppLink
    >.
  </p>
  <p>It looks like this:</p>
  <img src="/example.png" />
  <p>
    Triple Yang uses the same rules as Yin-Yang but involves 3 colors, making
    for a puzzle that feels surprisingly different. Solving it tends to involve
    much less direct pattern recognition and much more interesting and subtle
    geometric intuition. At the same time, Triple Yang has a more complex
    theory, which is often needed to make the global deductions that underpin
    the harder puzzles. [TODO: add help section]
  </p>
  <p>
    Note that all puzzles available here have been generated by a script that
    uses Z3 Theorem Prover to systematically remove as many clues as possible
    while still keeping the solution unique. This means they may unexpectedly
    range between very easy and very difficult &mdash; please feel free to skip
    a puzzle if you're stuck. I sorted them by decreasing number of clues,
    hoping that might reflect increasing difficulty.
  </p>
  <h1 class="text-lg font-bold">Rules</h1>
  <ol class="list-inside list-decimal">
    <li>Every cell must be filled with one of 3 colors.</li>
    <li
      >All cells of the same color must be connected orthogonally into a single
      group.
    </li>
    <li>2x2 squares of cells of the same color are not allowed.</li>
    <li
      >There must be at least 1 cell of each color.
      <p class="text-sm text-slate-500">
        (this is really a limitation of my generator; puzzles available here
        always have at least 1 clue of each color)
      </p>
    </li>
  </ol>
</template>
